"""initial schema

Revision ID: 4460a587c437
Revises: 
Create Date: 2026-07-07 11:57:17.733265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4460a587c437'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('analytics_daily',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('automated_count', sa.Integer(), nullable=False),
    sa.Column('human_intervention_count', sa.Integer(), nullable=False),
    sa.Column('avg_processing_seconds', sa.Float(), nullable=False),
    sa.Column('sla_breaches', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_daily_date'), 'analytics_daily', ['date'], unique=False)
    op.create_index(op.f('ix_analytics_daily_tenant_id'), 'analytics_daily', ['tenant_id'], unique=False)
    op.create_table('confidence_scores',
    sa.Column('subject_type', sa.String(length=50), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('breakdown_json', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_confidence_scores_subject_id'), 'confidence_scores', ['subject_id'], unique=False)
    op.create_index(op.f('ix_confidence_scores_tenant_id'), 'confidence_scores', ['tenant_id'], unique=False)
    op.create_table('customer_packs',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('manifest_path', sa.String(length=500), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_packs_name'), 'customer_packs', ['name'], unique=False)
    op.create_index(op.f('ix_customer_packs_tenant_id'), 'customer_packs', ['tenant_id'], unique=False)
    op.create_table('customers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_tenant_id'), 'customers', ['tenant_id'], unique=False)
    op.create_table('destinations',
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destinations_tenant_id'), 'destinations', ['tenant_id'], unique=False)
    op.create_table('inboxes',
    sa.Column('connector_type', sa.String(length=50), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inboxes_tenant_id'), 'inboxes', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'REVIEWER', 'VIEWER', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('emails',
    sa.Column('inbox_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.String(length=500), nullable=False),
    sa.Column('sender', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=998), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_ref', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inbox_id'], ['inboxes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emails_inbox_id'), 'emails', ['inbox_id'], unique=False)
    op.create_index(op.f('ix_emails_message_id'), 'emails', ['message_id'], unique=False)
    op.create_index(op.f('ix_emails_tenant_id'), 'emails', ['tenant_id'], unique=False)
    op.create_table('rules',
    sa.Column('customer_pack_id', sa.UUID(), nullable=True),
    sa.Column('key', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_pack_id'], ['customer_packs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_customer_pack_id'), 'rules', ['customer_pack_id'], unique=False)
    op.create_index(op.f('ix_rules_key'), 'rules', ['key'], unique=False)
    op.create_index(op.f('ix_rules_tenant_id'), 'rules', ['tenant_id'], unique=False)
    op.create_table('attachments',
    sa.Column('email_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=150), nullable=False),
    sa.Column('storage_ref', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_email_id'), 'attachments', ['email_id'], unique=False)
    op.create_index(op.f('ix_attachments_tenant_id'), 'attachments', ['tenant_id'], unique=False)
    op.create_table('rule_versions',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('definition_yaml', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_versions_rule_id'), 'rule_versions', ['rule_id'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('email_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.Enum('RECEIVED', 'CLASSIFIED', 'VALIDATED', 'ROUTED_VALID', 'ROUTED_INVALID', 'ROUTED_REVIEW', 'COMPLETED', name='workflow_state'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_runs_email_id'), 'workflow_runs', ['email_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_tenant_id'), 'workflow_runs', ['tenant_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('workflow_run_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_events_workflow_run_id'), 'audit_events', ['workflow_run_id'], unique=False)
    op.create_table('documents',
    sa.Column('attachment_id', sa.UUID(), nullable=False),
    sa.Column('extracted_text_ref', sa.String(length=255), nullable=False),
    sa.Column('ocr_provider', sa.String(length=50), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_attachment_id'), 'documents', ['attachment_id'], unique=False)
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.create_table('notifications',
    sa.Column('workflow_run_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('template', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notifications_workflow_run_id'), 'notifications', ['workflow_run_id'], unique=False)
    op.create_table('classifications',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classifications_document_id'), 'classifications', ['document_id'], unique=False)
    op.create_index(op.f('ix_classifications_tenant_id'), 'classifications', ['tenant_id'], unique=False)
    op.create_table('validation_results',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('rule_version_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PASS_', 'FAIL', 'WARN', name='validation_status'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_results_document_id'), 'validation_results', ['document_id'], unique=False)
    op.create_index(op.f('ix_validation_results_rule_version_id'), 'validation_results', ['rule_version_id'], unique=False)
    op.create_index(op.f('ix_validation_results_tenant_id'), 'validation_results', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_results_tenant_id'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_rule_version_id'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_document_id'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_classifications_tenant_id'), table_name='classifications')
    op.drop_index(op.f('ix_classifications_document_id'), table_name='classifications')
    op.drop_table('classifications')
    op.drop_index(op.f('ix_notifications_workflow_run_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_attachment_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_events_workflow_run_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_workflow_runs_tenant_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_email_id'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_rule_versions_rule_id'), table_name='rule_versions')
    op.drop_table('rule_versions')
    op.drop_index(op.f('ix_attachments_tenant_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_email_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_rules_tenant_id'), table_name='rules')
    op.drop_index(op.f('ix_rules_key'), table_name='rules')
    op.drop_index(op.f('ix_rules_customer_pack_id'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_emails_tenant_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_message_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_inbox_id'), table_name='emails')
    op.drop_table('emails')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_inboxes_tenant_id'), table_name='inboxes')
    op.drop_table('inboxes')
    op.drop_index(op.f('ix_destinations_tenant_id'), table_name='destinations')
    op.drop_table('destinations')
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_customer_packs_tenant_id'), table_name='customer_packs')
    op.drop_index(op.f('ix_customer_packs_name'), table_name='customer_packs')
    op.drop_table('customer_packs')
    op.drop_index(op.f('ix_confidence_scores_tenant_id'), table_name='confidence_scores')
    op.drop_index(op.f('ix_confidence_scores_subject_id'), table_name='confidence_scores')
    op.drop_table('confidence_scores')
    op.drop_index(op.f('ix_analytics_daily_tenant_id'), table_name='analytics_daily')
    op.drop_index(op.f('ix_analytics_daily_date'), table_name='analytics_daily')
    op.drop_table('analytics_daily')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
